"""LightScan v2.0 PHANTOM — Reporter (JSON·MD·HTML) | Developer: Light"""
import json, time, os, re
from datetime import datetime
from collections import defaultdict

SEV_COLORS = {"CRITICAL":"#ff2d55","HIGH":"#ff6b35","MEDIUM":"#ffd60a","LOW":"#30d158","INFO":"#636366"}
SEV_EMOJI  = {"CRITICAL":"🔴","HIGH":"🟠","MEDIUM":"🟡","LOW":"🟢","INFO":"⚪"}


def _group_results(results):
    """
    Group duplicate findings:
      - Same module + same param → merge URLs into one row with count
      - Keeps CRITICAL/unique findings ungrouped
    Returns list of dicts with optional 'count' and 'urls' fields.
    """
    grouped = []
    buckets = defaultdict(list)

    for r in results:
        detail = str(r.get("detail", ""))
        mod    = r.get("module", "")
        sev    = r.get("severity", "")

        # Extract param= from detail for grouping key
        param_m = re.search(r'param=(\S+)', detail)
        param   = param_m.group(1) if param_m else ""

        # Group same module+param+severity — but not CRITICAL (always show individually)
        if param and sev != "CRITICAL":
            key = f"{mod}|{sev}|{param}"
            buckets[key].append(r)
        else:
            grouped.append(r)  # CRITICAL or no param — show raw

    for key, items in buckets.items():
        if len(items) == 1:
            grouped.append(items[0])
        else:
            # Merge: take first item, add count + url list
            base   = dict(items[0])
            urls   = []
            for it in items:
                d = str(it.get("detail",""))
                # Extract URL from detail
                url_m = re.search(r'https?://\S+', d)
                if url_m: urls.append(url_m.group(0))
            param_m = re.search(r'param=(\S+)', str(base.get("detail","")))
            param   = param_m.group(1) if param_m else "?"
            mod     = base.get("module","")
            # Build a clean grouped detail
            raw_payload = (items[0].get("payload","") or
                           items[0].get("extra",{}).get("payload","") or
                           items[0].get("extra",{}).get("raw_payload",""))
            hint = raw_payload[:40] if raw_payload else _payload_hint(str(items[0].get("detail","")))
            base["detail"] = f"param={param} ({len(items)} URLs) — {hint}"
            base["count"]   = len(items)
            base["urls"]    = urls[:10]
            grouped.append(base)

    # Re-sort by severity order
    SEV_ORDER = {"CRITICAL":0,"HIGH":1,"MEDIUM":2,"LOW":3,"INFO":4}
    grouped.sort(key=lambda r: SEV_ORDER.get(r.get("severity","INFO"), 5))
    return grouped


def _payload_hint(detail: str) -> str:
    """Extract payload= or first meaningful token from a detail string."""
    m = re.search(r'payload=(\S+)', detail)
    if m: return m.group(1)[:40]
    m = re.search(r'db=(\S+)', detail)
    if m: return f"db={m.group(1)}"
    return detail[:40]


def to_markdown(results, meta):
    now    = datetime.fromtimestamp(meta.get("timestamp", time.time()))
    target = meta.get("target", "N/A")
    dur    = meta.get("duration", 0)
    grouped = _group_results(results)

    lines = [
        "# ⚡ LightScan v2.0 PHANTOM — Scan Report",
        f"> **Target:** `{target}`  ",
        f"> **Date:** {now.strftime('%Y-%m-%d %H:%M:%S')}  ",
        f"> **Duration:** {dur:.2f}s  ",
        f"> **Findings:** {len(results)} ({len(grouped)} grouped)",
        "", "---", "",
    ]

    for sev in ("CRITICAL","HIGH","MEDIUM","LOW","INFO"):
        group = [r for r in grouped if r.get("severity") == sev]
        if not group: continue
        lines.append(f"## {SEV_EMOJI.get(sev,'')} {sev} ({len(group)})")
        lines.append("| Module | Target | Port | Detail |")
        lines.append("|--------|--------|------|--------|")
        for r in group:
            det = str(r.get("detail","")).replace("|","\\|")
            cnt = r.get("count","")
            cnt_str = f" `×{cnt}`" if cnt else ""
            lines.append(
                f"| `{r.get('module','')}` | `{r.get('target','')}` "
                f"| `{r.get('port','')}` | {det}{cnt_str} |"
            )
            # Show URL list for grouped findings
            for url in r.get("urls",[]):
                lines.append(f"|  |  |  | ↳ `{url}` |")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by LightScan v2.0 PHANTOM — Developer: Light (Neok1ra)*")
    return "\n".join(lines)


def to_html(results, meta):
    now     = datetime.fromtimestamp(meta.get("timestamp", time.time()))
    target  = meta.get("target", "N/A")
    dur     = meta.get("duration", 0)
    grouped = _group_results(results)

    rows = ""
    for r in grouped:
        sev = r.get("severity","INFO")
        col = SEV_COLORS.get(sev,"#636366")
        mod = r.get("module","")
        tgt = r.get("target","")
        prt = r.get("port","")
        det = str(r.get("detail","")).replace("<","&lt;").replace(">","&gt;")
        cnt = r.get("count","")
        cnt_badge = (f'<span style="background:#333;color:#ff9f0a;'
                     f'padding:.1rem .4rem;border-radius:3px;font-size:.65rem">'
                     f'×{cnt}</span> ') if cnt else ""
        url_rows = ""
        for url in r.get("urls",[]):
            url_esc = url.replace("<","&lt;").replace(">","&gt;")
            url_rows += (f'<tr><td colspan="2"></td><td colspan="4" class="d" '
                         f'style="color:#555;padding:.2rem .8rem">'
                         f'↳ <a href="{url_esc}" style="color:#636366">{url_esc}</a></td></tr>')
        rows += (f'<tr>'
                 f'<td><span class="b" style="background:{col}">{sev}</span></td>'
                 f'<td><code>{mod}</code></td>'
                 f'<td>{tgt}</td>'
                 f'<td>{prt}</td>'
                 f'<td class="d">{cnt_badge}{det}</td>'
                 f'</tr>{url_rows}')

    crit = sum(1 for r in results if r.get("severity")=="CRITICAL")
    high = sum(1 for r in results if r.get("severity")=="HIGH")
    med  = sum(1 for r in results if r.get("severity")=="MEDIUM")
    low  = sum(1 for r in results if r.get("severity") in ("LOW","INFO"))

    return f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>LightScan — {target}</title>
<style>
:root{{--bg:#0d0d0d;--s:#1a1a1a;--b:#2a2a2a;--r:#ff2d55;--t:#e0e0e0;--m:#636366}}
*{{box-sizing:border-box;margin:0;padding:0}}
body{{background:var(--bg);color:var(--t);font-family:'Courier New',monospace;padding:2rem}}
h1{{color:var(--r);font-size:1.6rem;letter-spacing:.1em;margin-bottom:.3rem}}
.sub{{color:var(--m);font-size:.8rem;margin-bottom:1.5rem;letter-spacing:.05em}}
.meta{{color:var(--m);font-size:.8rem;margin-bottom:1.5rem}}
.meta span{{margin-right:2rem}}
.stats{{display:flex;gap:1.5rem;margin-bottom:2rem;flex-wrap:wrap}}
.stat{{background:var(--s);border:1px solid var(--b);padding:.8rem 1.2rem;border-radius:6px;min-width:100px;text-align:center}}
.sn{{font-size:1.8rem;font-weight:bold}}
.sl{{color:var(--m);font-size:.65rem;letter-spacing:.1em;margin-top:.2rem}}
table{{width:100%;border-collapse:collapse;background:var(--s)}}
th{{background:#111;color:var(--r);text-align:left;padding:.6rem .8rem;font-size:.72rem;letter-spacing:.08em;border-bottom:1px solid var(--b)}}
td{{padding:.5rem .8rem;font-size:.78rem;border-bottom:1px solid var(--b);vertical-align:top}}
tr:hover td{{background:#1f1f1f}}
code{{color:#ff9f0a;background:#111;padding:.15rem .4rem;border-radius:3px;font-size:.75rem}}
.b{{padding:.2rem .5rem;border-radius:3px;font-size:.65rem;font-weight:bold;color:#000;white-space:nowrap}}
.d{{color:#aaa;font-size:.75rem;word-break:break-all}}
footer{{margin-top:2rem;text-align:center;color:var(--m);font-size:.7rem;padding-top:1rem;border-top:1px solid var(--b)}}
</style>
</head><body>
<h1>⚡ LightScan v2.0 PHANTOM</h1>
<div class="sub">Async Network Recon &amp; Attack Framework · Developer: Light (Neok1ra)</div>
<div class="meta">
  <span>🎯 <strong style="color:#e0e0e0">{target}</strong></span>
  <span>📅 {now.strftime('%Y-%m-%d %H:%M:%S')}</span>
  <span>⏱ {dur:.1f}s</span>
</div>
<div class="stats">
  <div class="stat"><div class="sn">{len(results)}</div><div class="sl">TOTAL</div></div>
  <div class="stat"><div class="sn" style="color:#ff2d55">{crit}</div><div class="sl">CRITICAL</div></div>
  <div class="stat"><div class="sn" style="color:#ff6b35">{high}</div><div class="sl">HIGH</div></div>
  <div class="stat"><div class="sn" style="color:#ffd60a">{med}</div><div class="sl">MEDIUM</div></div>
  <div class="stat"><div class="sn" style="color:#636366">{low}</div><div class="sl">LOW/INFO</div></div>
</div>
<table>
  <thead><tr><th>SEV</th><th>MODULE</th><th>TARGET</th><th>PORT</th><th>DETAIL</th></tr></thead>
  <tbody>{rows}</tbody>
</table>
<footer>LightScan v2.0 PHANTOM · Developer: Light (Neok1ra)</footer>
</body></html>"""


class Reporter:
    def __init__(self, output_dir="."):
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)

    def save(self, results, meta, basename="lightscan_report"):
        raw = [r.to_dict() if hasattr(r,"to_dict") else r for r in results]
        jp  = os.path.join(self.output_dir, f"{basename}.json")
        mp  = os.path.join(self.output_dir, f"{basename}.md")
        hp  = os.path.join(self.output_dir, f"{basename}.html")
        with open(jp,"w") as f: json.dump({"meta":meta,"results":raw}, f, indent=2)
        with open(mp,"w") as f: f.write(to_markdown(raw, meta))
        with open(hp,"w") as f: f.write(to_html(raw, meta))
        print(f"\n\033[38;5;196m[REPORT]\033[0m ↳ JSON: {jp}")
        print(f"\033[38;5;196m[REPORT]\033[0m ↳ MD:   {mp}")
        print(f"\033[38;5;196m[REPORT]\033[0m ↳ HTML: {hp}")
        return jp, mp, hp
